---
- name: Install dependencies
  apt:
    name: 
      - python3
      - python3-dev 
      - python3-venv 
      - python3-pip 
      - libffi-dev 
      - libssl-dev
    state: latest

- name: Add the user 'homeassistant' with a specific uid and a primary group of 'admin'
  user:
    name: homeassistant
    groups: dialout,gpio,i2c

- name: Create a directory for home assistant
  file:
    path: /srv/homeassistant
    state: directory
    owner: homeassistant

- name: create virtual environment
  command: "{{ item }}"
  with_items:
    - "bash -c \"python3 -m venv /srv/homeassistant\""
  become: yes
  become_user: homeassistant

- name: Download and install wheel
  command: "{{ item }}"
  with_items:
    - "bash -c \"source /srv/homeassistant/bin/activate && pip install --upgrade wheel\""
  become: yes
  become_user: homeassistant

- name: Download and install homeassistant
  command: "{{ item }}"
  with_items:
    - "bash -c \"source /srv/homeassistant/bin/activate && pip install --upgrade homeassistant\""
  become: yes
  become_user: homeassistant

- name: Setup systemd for homeassistant
  become: true
  template:
    src: homeassistant.service
    dest: /etc/systemd/system/homeassistant.service
    mode: 0644

- name: Ensure my daemon homeassistant is started
  become: true
  systemd:
    name: homeassistant
    state: started
    enabled: yes
    daemon-reload: yes
    no_block: yes